In [6]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
import joblib as jb
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [7]:
data = pd.read_csv("../../Data/Fertilizer Prediction.csv")
data_en = data.drop("Fertilizer Name",axis=1)
data_en

,Temparature,Humidity,Moisture,Soil Type,Crop Type,Nitrogen,Potassium,Phosphorous
0,26,52,38,Sandy,Maize,37,0,0
1,29,52,45,Loamy,Sugarcane,12,0,36
2,34,65,62,Black,Cotton,7,9,30
3,32,62,34,Red,Tobacco,22,0,20
4,28,54,46,Clayey,Paddy,35,0,21
...,...,...,...,...,...,...,...,...
94,25,50,32,Clayey,Pulses,24,0,111
95,30,60,27,Red,Tobacco,4,17,112
96,38,72,51,Loamy,Wheat,39,0,113
97,36,60,43,Sandy,Millets,15,0,114
98,29,58,57,Black,Sugarcane,12,0,115

In [8]:
data_en.columns

Index(['Temparature', 'Humidity ', 'Moisture', 'Soil Type', 'Crop Type',
       'Nitrogen', 'Potassium', 'Phosphorous'],
      dtype='object')

In [9]:

columns_to_encode = ['Soil Type', 'Crop Type']
columns_to_scale = [col for col in data_en.columns if col not in columns_to_encode]

# Define transformers for encoding and scaling
encoder = OneHotEncoder(handle_unknown='ignore')
scaler = StandardScaler()

# Create a ColumnTransformer
preprocessor = ColumnTransformer(
    transformers=[
        ('scaler', scaler, columns_to_scale),
        ('onehot', encoder, columns_to_encode)
    ])

# Fit and transform the data
transformed_data = preprocessor.fit_transform(data_en)

# Convert the transformed data to a DataFrame
columns_encoded = preprocessor.named_transformers_['onehot'].get_feature_names_out(columns_to_encode)
columns_scaled = columns_to_scale
columns_transformed = columns_scaled +  list(columns_encoded) 
data_transformed = pd.DataFrame(transformed_data, columns=columns_transformed)

data_transformed

,Temparature,Humidity,Moisture,Nitrogen,Potassium,Phosphorous,Soil Type_Black,Soil Type_Clayey,Soil Type_Loamy,Soil Type_Red,...,Crop Type_Ground Nuts,Crop Type_L,Crop Type_Maize,Crop Type_Millets,Crop Type_Oil seeds,Crop Type_Paddy,Crop Type_Pulses,Crop Type_Sugarcane,Crop Type_Tobacco,Crop Type_Wheat
0,-1.229084,-1.230737,-0.462064,1.567539,-0.584910,-2.318979,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,-0.368145,-1.230737,0.162128,-0.598658,-0.584910,-1.056400,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2,1.066752,1.006492,1.678023,-1.031898,0.970777,-1.266830,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.492793,0.490209,-0.818745,0.267821,-0.584910,-1.617546,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,-0.655125,-0.886548,0.251298,1.394244,-0.584910,-1.582474,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,-1.516063,-1.574926,-0.997086,0.441117,-0.584910,1.573972,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
95,-0.081166,0.146020,-1.442938,-1.291841,2.353610,1.609044,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
96,2.214670,2.211154,0.697150,1.740835,-0.584910,1.644116,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
97,1.640711,0.146020,-0.016213,-0.338715,-0.584910,1.679187,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
98,-0.368145,-0.198169,1.232171,-0.598658,-0.584910,1.714259,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

In [10]:
data_transformed.columns

Index(['Temparature', 'Humidity ', 'Moisture', 'Nitrogen', 'Potassium',
       'Phosphorous', 'Soil Type_Black', 'Soil Type_Clayey', 'Soil Type_Loamy',
       'Soil Type_Red', 'Soil Type_Sandy', 'Crop Type_Barley',
       'Crop Type_Cotton', 'Crop Type_Ground Nuts', 'Crop Type_L',
       'Crop Type_Maize', 'Crop Type_Millets', 'Crop Type_Oil seeds',
       'Crop Type_Paddy', 'Crop Type_Pulses', 'Crop Type_Sugarcane',
       'Crop Type_Tobacco', 'Crop Type_Wheat'],
      dtype='object')

In [11]:
jb.dump(preprocessor,"output/model/preprocessor.joblib")

['output/model/preprocessor.joblib']

In [11]:
data_transformed["Fertilizer Name"] = data["Fertilizer Name"]
data_transformed.to_csv("output/processed_data/data_scaled.csv",index=False)
data_transformed

,Temparature,Humidity,Moisture,Nitrogen,Potassium,Phosphorous,Soil Type_Black,Soil Type_Clayey,Soil Type_Loamy,Soil Type_Red,...,Crop Type_L,Crop Type_Maize,Crop Type_Millets,Crop Type_Oil seeds,Crop Type_Paddy,Crop Type_Pulses,Crop Type_Sugarcane,Crop Type_Tobacco,Crop Type_Wheat,Fertilizer Name
0,-1.229084,-1.230737,-0.462064,1.567539,-0.584910,-2.318979,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Urea
1,-0.368145,-1.230737,0.162128,-0.598658,-0.584910,-1.056400,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,DAP
2,1.066752,1.006492,1.678023,-1.031898,0.970777,-1.266830,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,14-35-14
3,0.492793,0.490209,-0.818745,0.267821,-0.584910,-1.617546,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,28-28
4,-0.655125,-0.886548,0.251298,1.394244,-0.584910,-1.582474,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,Urea
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,-1.516063,-1.574926,-0.997086,0.441117,-0.584910,1.573972,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,28-28
95,-0.081166,0.146020,-1.442938,-1.291841,2.353610,1.609044,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,10/26/2026
96,2.214670,2.211154,0.697150,1.740835,-0.584910,1.644116,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,Urea
97,1.640711,0.146020,-0.016213,-0.338715,-0.584910,1.679187,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,DAP
98,-0.368145,-0.198169,1.232171,-0.598658,-0.584910,1.714259,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,20-20

In [5]:
# columns_to_encode = ['Soil Type', 'Crop Type']

# # Extract the columns to be encoded
# data_to_encode = data[columns_to_encode]

# # Initialize the OneHotEncoder
# encoder = OneHotEncoder()

# # Fit and transform the data
# encoded_data = encoder.fit_transform(data_to_encode)

# # Convert the encoded data to a DataFrame
# encoded_df = pd.DataFrame(encoded_data.toarray(), columns=encoder.get_feature_names_out(columns_to_encode))
# encoded_df
# data_numerical= data_en.drop(columns_to_encode, axis=1)
# scaler = StandardScaler()
# array_scaled = scaler.fit_transform(data_numerical)
# data_scaled = pd.DataFrame(array_scaled,columns=data_numerical.columns)
# data_scaled
# scaled_data=pd.concat([data_scaled, encoded_df], axis=1)
# jb.dump(scaler,"output/model/scaler.joblib")
# jb.dump(encoder,"output/model/onehotencoder.joblib")